// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
#nullable disable

namespace Infrastructure.Persistence.Migrations;

[DbContext(typeof(SichiDbContext))]
partial class SichiDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.0")
            .HasAnnotation("Relational:MaxIdentifierLength", 64);

        modelBuilder.Entity("Domain.Entities.AuditLog", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Action")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Detail")
                    .IsRequired()
                    .HasColumnType("longtext");

                b.Property<int>("EntityId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<int>("UserId")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("AuditLogs");

                b.HasOne("Domain.Entities.User", "User")
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Domain.Entities.MediaItem", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<string>("Checksum")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)")
                    .HasDefaultValue("");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<int>("DurationSeconds")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("varchar(255)");

                b.Property<string>("FilePath")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("varchar(500)");

                b.Property<long>("FileSize")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasDefaultValue(0L);

                b.Property<string>("MediaType")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasDefaultValue("Video");

                b.HasKey("Id");

                b.ToTable("MediaItems");
            });

        modelBuilder.Entity("Domain.Entities.Playlist", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<bool>("IsActive")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(true);

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<int>("Version")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(1);

                b.HasKey("Id");

                b.ToTable("Playlists");
            });

        modelBuilder.Entity("Domain.Entities.PlaylistMedia", b =>
            {
                b.Property<int>("PlaylistId")
                    .HasColumnType("int");

                b.Property<int>("MediaItemId")
                    .HasColumnType("int");

                b.Property<int?>("OverrideDuration")
                    .HasColumnType("int");

                b.Property<int>("SortOrder")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .HasDefaultValue(0);

                b.HasKey("PlaylistId", "MediaItemId");

                b.HasIndex("MediaItemId");

                b.ToTable("PlaylistMedias");
            });

        modelBuilder.Entity("Domain.Entities.Screen", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<int?>("CurrentPlaylistId")
                    .HasColumnType("int");

                b.Property<string>("DeviceId")
                    .IsRequired()
                    .ValueGeneratedOnAdd()
                    .HasMaxLength(20)
                    .HasColumnType("varchar(20)")
                    .HasDefaultValue("");

                b.Property<bool>("IsApproved")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(false);

                b.Property<bool>("IsOnline")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("tinyint(1)")
                    .HasDefaultValue(false);

                b.Property<DateTime?>("LastPing")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)");

                b.Property<string>("ScreenKey")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("varchar(64)");

                b.HasKey("Id");

                b.HasIndex("CurrentPlaylistId");

                b.HasIndex("ScreenKey")
                    .IsUnique();

                b.ToTable("Screens");
            });

        modelBuilder.Entity("Domain.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime(6)");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(150)
                    .HasColumnType("varchar(150)");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("varchar(255)");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("Users");
            });

        modelBuilder.Entity("Domain.Entities.PlaylistMedia", b =>
            {
                b.HasOne("Domain.Entities.MediaItem", "MediaItem")
                    .WithMany("PlaylistMedias")
                    .HasForeignKey("MediaItemId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("Domain.Entities.Playlist", "Playlist")
                    .WithMany("PlaylistMedias")
                    .HasForeignKey("PlaylistId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("MediaItem");

                b.Navigation("Playlist");
            });

        modelBuilder.Entity("Domain.Entities.Screen", b =>
            {
                b.HasOne("Domain.Entities.Playlist", "CurrentPlaylist")
                    .WithMany()
                    .HasForeignKey("CurrentPlaylistId")
                    .OnDelete(DeleteBehavior.SetNull);

                b.Navigation("CurrentPlaylist");
            });

        modelBuilder.Entity("Domain.Entities.MediaItem", b =>
            {
                b.Navigation("PlaylistMedias");
            });

        modelBuilder.Entity("Domain.Entities.Playlist", b =>
            {
                b.Navigation("PlaylistMedias");
            });
#pragma warning restore 612, 618
    }
}
